# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: AWS Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    # Share artifact inside workflow
    - name: Share artifact inside workflow
      uses: actions/upload-artifact@v1
      with:
        name: react-github-actions-build
        path: build
    - name: Share artifact inside workflow
      uses: actions/upload-artifact@v1
      with:
        name: react-github-actions-build
        path: build
  
  deploy-s3:
    name: Deploy to S3 bucket
    runs-on: ubuntu-latest
    # When application is successfully tested and build has been generated
    # Then we can start with deployment
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
      # Set the credentials from repository settings/secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # Copy the files from build folder to the S3 bucket
      - name: Deploy to S3
        run: aws s3 sync . s3://csbc1040assignment2 --delete
        working-directory: react-github-actions-build

  deploy-gcs:
    runs-on: ubuntu-latest
    name: Deploy to GCS bucket
    needs: build
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
      
      - name: Auth to Gcloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Upload build folder to bucket
        id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: react-github-actions-build
          destination: 'csbc1040assignment2.rajarv.com'
          parent: false



